_dev:
    - !C.project
        name : "gov_api"
        root : "${HOME}/devspace/gov_api"
    - !C.version
        file : "./version.txt"
    - !C.git
        remote : "ssh://git@git.dzhcool.com:22/data/gitdata/announce"
